### ISSUE TITLE
img attribute 

### ISSUE THREAD

**Issue by ghassanmas** [FACN3/WDYNAC#25]
The src of attribute of in the img element in the following lines shouldn't be empty if no source is avaiable in the current time, set it to  `src =""`. 
https://github.com/FACN3/WDYNAC/blob/master/index.html#L78
https://github.com/FACN3/WDYNAC/blob/master/index.html#L84
https://github.com/FACN3/WDYNAC/blob/master/index.html#L90

**Comment by finnhodgkin** [comment]
Try to only add elements when you know what content they will contain. It's really easy to forget things that you've delegated to the "oh yeah we'll fix that later" pile. If you start with high quality, relevant code it's _much_ easier to maintain quality throughout a project.
