### ISSUE TITLE
Strive for even contribution amongst team members

### ISSUE THREAD

**Issue by yvonne-liu** [FACN3/WDYNAC#37]
A good reminder to switch up working each other's devices even when pair programming 👍 :

https://github.com/FACN3/WDYNAC/graphs/contributors

**Comment by finnhodgkin** [comment]
To be fair part of this is down to @Amirk390 not having his git linked correctly on desktop #18. Even bearing that in mind, the graph is still pretty uneven.

**Comment by idantb101** [comment]
@finnhodgkin :+1:
